### ISSUE TITLE
pip install neural_renderer_pytorch问题

### ISSUE THREAD

**Issue by GitHubmalajava** [lstcutong/neural_renderer_pytorch-win10#1]
@lstcutong ，
我好像也是第一个问题，开始觉得是cuda版本过高，但是从v11.1改成9.2还是报错nvcc.exe的问题，
所以我想知道你这个代码是直接下载之后来运行setup.py吗，还是改成你说的版本就行啊

**Comment by lstcutong** [comment]
> @lstcutong ，
> 我好像也是第一个问题，开始觉得是cuda版本过高，但是从v11.1改成9.2还是报错nvcc.exe的问题，
> 所以我想知道你这个代码是直接下载之后来运行setup.py吗，还是改成你说的版本就行啊

我这边10.1没啥问题，你试试。然后我readme里的三个都要弄，版本，pytorch源码，以及neural_mesh_renderer的源码都要改才行。

**Comment by GitHubmalajava** [comment]
@lstcutong ，
vc的版本是要自己更新吗，用conda下载环境的好像都是2015

**Comment by GitHubmalajava** [comment]
vs的版本要自己更新吗，用conda下载的环境都是2015

**Comment by GitHubmalajava** [comment]
@lstcutong ，
我用最新版本的torch和cuda，根据你的代码成功装上。
太强了，博主！！！！
感谢感谢！！！！
